#!/bin/bash
#
#   @(#) Print Renge Kunai quotes
#
#   Author:
#       844196 (@84____)
#
#   License:
#       MIT
#


# initialize
## option
set -u
set -e

## about me
readonly ME="${0##*/}"
readonly VERSION="0.2"
readonly basedir="${0%/*}"

## usage
function usage() {
    cat <<-EOF 1>&2
	Usage:
	    ${ME} [optinos]
	
	Argument:
	    No argument.
	
	Options:
	    -v, --version   Print version and exit successfully.
	    -h, --help      Print this help and exit successfully.
	EOF
    return 0
}

## error
function error() {
    echo "${ME}: ${1}" 1>&2
    exit "${2:-1}"
}


# get and check argument, options
## get option
for OPTIONS in "${@-}"
do
    case "${OPTIONS}" in
        '-h'|'--help' )
            usage
            exit 0
            ;;
        '-v'|'--version' )
            echo "${VERSION}" 1>&2
            exit 0
            ;;
        -* )
            error "illegal option -- '${1}'" "-1"
            ;;
    esac
done


# fortunerenge
## common function
function createRandomNumber() {
    # shellcheck disable=SC2086
    awk 'BEGIN{
        srand();
        print substr(rand(), 3) % '${1:-1}'
    }'
    return 0
}

## check renge-quotes
if [[ ! -e "${basedir}/renge-quotes" ]]; then
    error "internal error -- 'no quotes file'" "2"
fi

## quotes into array
while read line
do
    quotes+=( "${line}" )
done <"${basedir}/renge-quotes"

## print quote
echo "${quotes[$(createRandomNumber "${#quotes[@]}")]}"


# exit
exit 0
